### ISSUE TITLE
Pip needs to be upgraded to install chatterbox extension

### ISSUE THREAD

**Issue by camcop** [rsxdalv/TTS-WebUI#516]
After deploying TTS-WebUI using docker compose I tried to install the chatterbox extension via the UI (and via command line) and repeatedly ran into the error (full output below):

```bash
ERROR: No matching distribution found for chatterbox-tts (unavailable)
```

I no longer had this issue after running:

`pip install --upgrade pip setuptools wheel`

I don't think this is specific to my environment given I'm running it via docker (but I could be wrong). I also had an issue installing the Kokoro extension that this seemed to fix too.

Two slightly separate questions:
 1. Where are extensions installed? I'd like to bind mount that directory if possible so I don't have to reinstall the extensions every time the container is recreated (or at least the location that extensions download models to)
 2. Can I enable the OpenAI API in the docker `compose.yml`? Or do I have to do it manually in the UI every the container restarts?

I can't see any documentation in relation to the above. 

**Full error output**:
```bash
root@627029e3f064:/app/tts-webui# pip install git+https://github.com/rsxdalv/extension_chatterbox@main
Collecting git+https://github.com/rsxdalv/extension_chatterbox@main
  Cloning https://github.com/rsxdalv/extension_chatterbox (to revision main) to /tmp/pip-req-build-j1du3oy1
  Running command git clone --filter=blob:none --quiet https://github.com/rsxdalv/extension_chatterbox /tmp/pip-req-build-j1du3oy1
  Resolved https://github.com/rsxdalv/extension_chatterbox to commit 30da0826f73ef525e70d53d69fcd584f57cf15e2
  Preparing metadata (setup.py) ... done
Collecting chatterbox-tts@ git+https://github.com/rsxdalv/chatterbox@loosen
  Cloning https://github.com/rsxdalv/chatterbox (to revision loosen) to /tmp/pip-install-bppsn5t5/chatterbox-tts_3a20d8f480df438ba86072814742c7dd
  Running command git clone --filter=blob:none --quiet https://github.com/rsxdalv/chatterbox /tmp/pip-install-bppsn5t5/chatterbox-tts_3a20d8f480df438ba86072814742c7dd
  Running command git checkout -b loosen --track origin/loosen
  Switched to a new branch 'loosen'
  Branch 'loosen' set up to track remote branch 'loosen' from 'origin'.
  Resolved https://github.com/rsxdalv/chatterbox to commit d4bb20ab34354176455681e343cd7251d4a933a5
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package chatterbox-tts produced metadata for project name unknown. Fix your #egg=chatterbox-tts fragments.
Discarding git+https://github.com/rsxdalv/chatterbox@loosen: Requested unknown from git+https://github.com/rsxdalv/chatterbox@loosen (from extension-chatterbox==0.6.0) has inconsistent name: filename has 'chatterbox-tts', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement chatterbox-tts (unavailable) (from extension-chatterbox) (from versions: 0.1, 0.1.1)
ERROR: No matching distribution found for chatterbox-tts (unavailable)
```

**compose.yml**:
```yml
services:
  tts-webui:
    image: "ghcr.io/rsxdalv/tts-webui:main"
    restart: unless-stopped
    ports:
      - ${TTS_PORT:-7770}:7770
      # include React UI
      - ${UI_PORT:-3000}:3000
      - 7778:7778
    container_name: tts-webui
    environment:
      - HUGGINGFACE_HUB_CACHE=/home/ubuntu/.cache/huggingface/hub
      - XDG_CACHE_HOME=/home/ubuntu/.cache/xdg
    volumes:
      - /home/ubuntu/.tts-webui/data/models:/app/tts-webui/data/models
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
```
